# Default configuration of the PerfTest package
# ~ == nothing, empty value, used commonly for optional parameters
autoflops: true
save_folder: ".perftests"
save_test_results: true
max_saved_results: 10
verbose: true
suppress_output: true
regression:
  enabled: false
  save_failed_tests: false
  general_boundary:
    worse: 0.2
    better: ~
  custom_metrics_boundary: ~
fixed_threshold:
  enabled: true
  general_boundary:
    worse: 0.2
    better: ~
  custom_metrics_boundary: ~
roofline:
  enabled: true
  full_roofline: true
  plotting: true
  boundary:
    worse: 0.2
    better: ~
